### PR TITLE
statement rewriters use a cache

### PR DESCRIPTION
**Pull request by rudydai**
avoids doing redundant work in the lexer, since parsing a sql statement should be deterministic

### CODE REVIEW

File: src/main/java/org/skife/jdbi/v2/ColonPrefixNamedParamStatementRewriter.java [hunk 1]
```diff
@@ -41,6 +43,8 @@
  */
 public class ColonPrefixNamedParamStatementRewriter implements StatementRewriter
 {
+    private final Map<String, ParsedStatement> cache = new HashMap();
```
Comment (stevenschlansker) [inline src/main/java/org/skife/jdbi/v2/ColonPrefixNamedParamStatementRewriter.java]: This needs to be a `ConcurrentMap` I think?

File: src/main/java/org/skife/jdbi/v2/HashPrefixStatementRewriter.java [hunk 2]
```diff
@@ -39,6 +41,8 @@
  */
 public class HashPrefixStatementRewriter implements StatementRewriter
 {
+    private final Map<String, ParsedStatement> cache = new HashMap();
```
Comment (stevenschlansker) [inline src/main/java/org/skife/jdbi/v2/HashPrefixStatementRewriter.java]: `ConcurrentMap`?

**Comment by stevenschlansker** [comment]
Looks like there's a compilation error, and I think the current `Map` usage is not threadsafe.  Other than that, looks OK.

**Comment by rudydai** [comment]
changed the commit to use a concurrenthashmap instead, can't reproduce the compilation error locally though - and the method signature seems to match other invocations in the same test class. is there something I'm missing here?

**Comment by stevenschlansker** [comment]
The compile error is a merge conflict with #164 that Git didn't catch.

**Comment by rudydai** [comment]
thanks for the fixups :)

**Comment by stevenschlansker** [comment]
BTW, I switched it to a `Collections.synchronizedMap(new WeakHashMap<String, ParsedStatement>());` for the cache -- otherwise we may cause previously working applications that generate lots of SQL statements to crash.
