### ISSUE TITLE
IllegalArgumentException when a DAO is initialized (Java 8 support?)

### ISSUE THREAD

**Issue by natnan** [jdbi/jdbi#144]
I've been using jdbi via [dropwizard](https://github.com/dropwizard/dropwizard/tree/master/dropwizard-jdbi) for a while now. On dropwizard 0.7.1 version, it was using jdbi 2.55 and I had no problems.

Then when I upgraded my dropwizard to 0.8-rc2, they had updated jdbi to 2.57. I started having the following exception when I run some of my tests via gradle. (Was not happening when run on Intellij, but I think it was because how Intellij handles external libraries with multiple module projects)

*(Well, the stack trace was different as the cglib and asm libraries were external libraries and didn't have jdbi package names. It's a bit difficult to get the exact stack trace now.)*
```stacktrace
java.lang.IllegalArgumentException
	at org.skife.jdbi.cglib.asm.ClassReader.<init>(Unknown Source)
	at org.skife.jdbi.cglib.asm.ClassReader.<init>(Unknown Source)
	at org.skife.jdbi.cglib.asm.ClassReader.<init>(Unknown Source)
	at org.skife.jdbi.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61)
	at org.skife.jdbi.cglib.proxy.Enhancer.emitMethods(Enhancer.java:911)
	at org.skife.jdbi.cglib.proxy.Enhancer.generateClass(Enhancer.java:498)
	at org.skife.jdbi.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.skife.jdbi.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at org.skife.jdbi.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at org.skife.jdbi.cglib.proxy.Enhancer.create(Enhancer.java:285)
	at org.skife.jdbi.v2.sqlobject.SqlObject.buildSqlObject(SqlObject.java:78)
	at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.onDemand(SqlObjectBuilder.java:66)
	at org.skife.jdbi.v2.DBI.onDemand(DBI.java:350)
    ...
```

Gradle failing but not Intellij usually comes down to libraries clashing somehow, so I started digging into that and came across to [this stackoverflow question](http://stackoverflow.com/questions/27092857/cglib-throws-an-illegalargumentexception-when-enhancing-the-java-util-date-class). Figured it's something with java 8 support of asm, I came up with a temporary solution after many trial and errors:

```gradle
    compile('io.dropwizard:dropwizard-jdbi:0.8-rc2'){
        exclude group:'cglib'
    }
    compile 'cglib:cglib:3.1'
    compile 'org.ow2.asm:asm:5.0.3'
```

Now, dropwizard has a new version, rc3 and they have updated jdbi to 2.59. My temporary solution is not working anymore since jdbi has moved the sourcecode of asm and cglib into it's own package (or must be something like that as the classes' package name start with `org.skife.jdbi`). So I digged into the ClassReader code and I can see the difference between jdbi's asm and asm 5.0.3:

##### jdbi:
```java
public ClassReader(byte[] var1, int var2, int var3) {
    this.b = var1;
    if(this.readShort(var2 + 6) > 51) {
      throw new IllegalArgumentException();
    } else {
      this.a = new int[this.readUnsignedShort(var2 + 8)];
```

##### asm:
```java
 public ClassReader(final byte[] b, final int off, final int len) {
        this.b = b;
        // checks the class version
        if (readShort(off + 6) > Opcodes.V1_8) {
            throw new IllegalArgumentException();
        }
        // parses the constant pool
        items = new int[readUnsignedShort(off + 8)];
```

I'm not sure what exactly this code does, and why my DAO triggers this (I use Instants and Optionals that are specific to java 8) but it looks like there is a specific Java 8 check on the latest asm code. Any way to work around or fix?

**Comment by stevenschlansker** [comment]
So, this *should* be an easy fix.  But it's not for really dumb reasons.  But could you try out the latest `2.60-SNAPSHOT` (or a build of PR #145) and let me know if that fixes your issue?

**Comment by natnan** [comment]
Where can I find SNAPSHOT builds? They are not in maven-central, and am not sure where to grab it otherwise :).
Also, the build seemed to have failed.

**Comment by natnan** [comment]
This is what I get from `2.60-SNAPSHOT`
```
java.lang.NoClassDefFoundError: org/skife/jdbi/cglib/proxy/Callback
	at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.onDemand(SqlObjectBuilder.java:66)
	at org.skife.jdbi.v2.DBI.onDemand(DBI.java:350)
	at test.dao.DaoTest.test(DaoTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassNotFoundException: org.skife.jdbi.cglib.proxy.Callback
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
```

**Comment by natnan** [comment]
Tried to isolate the issue into a unit test on 2.59 but couldn't reproduce that way (still being reproduced in my dropwizard application though). Is it possible that org.skife.jdbi.cglib classes conflict with other libraries somehow? It doesn't make sense to me but maybe Java has its way of doing things that I don't know..

**Comment by stevenschlansker** [comment]
Hi @natnan, so the problem is:
`cglib` depends on the `ASM` package version 3.x
ASM 3.x has known issues running with Java 8, specifically that ClassReader IllegalArgumentException.  It's fixed in ASM 5.0.2.

But we depend on `cglib-nodep`, the 'no dependencies' version, which [shades](http://maven.apache.org/plugins/maven-shade-plugin/) the bad version of ASM in.

We can fix it by switching back to the regular `cglib`, but the base POM bans it.
So we have to remove this ban: https://github.com/basepom/basepom/pull/14
As soon as that gets merged in by @hgschmie, I can build the new JDBI.

**Comment by stevenschlansker** [comment]
In the meantime, it would be very helpful if you could test this fix out and confirm it fixes your problem.  The easiest way would be to first check out the above linked Basepom project, switch to the branch, and do `mvn install`.
Then do the same for this PR, check out jdbi, and switch to the branch, and do `mvn install`.  Then test out `2.60-SNAPSHOT` and report back.  Make sense?

**Comment by natnan** [comment]
> But we depend on cglib-nodep, the 'no dependencies' version, which shades the bad version of ASM in.

Yes, that why I was doing the following on 2.57, but it doesn't work on 2.59 anymore.
```
compile('io.dropwizard:dropwizard-jdbi:0.8-rc2'){
        exclude group:'cglib'
    }
    compile 'cglib:cglib:3.1'
    compile 'org.ow2.asm:asm:5.0.3'
```

After long fights with java6 and maven, I managed to install basepom and jdbi (had to skip tests though) with their branches into my local repository; and tried to use it in my application. I still get

```
java.lang.NoClassDefFoundError: org/skife/jdbi/cglib/proxy/Callback
	at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.onDemand(SqlObjectBuilder.java:66)
	at org.skife.jdbi.v2.DBI.onDemand(DBI.java:350)
        .....
```

Also, how come everything was working with 2.55 just fine, without any workarounds?

**Comment by natnan** [comment]
removed
```xml
                                <relocation>
                                    <pattern>net.sf.cglib</pattern>
                                    <shadedPattern>org.skife.jdbi.cglib</shadedPattern>
                                </relocation>
```
from your PR and `mvn install`ed again. Now I'm back to 

```
java.lang.IllegalArgumentException
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.objectweb.asm.ClassReader.<init>(Unknown Source)
```

**Comment by stevenschlansker** [comment]
Without any changes (especially the relocation bit) can you give the full stack trace for the failure?  Would it be possible to create a small test case showing the problem?

**Comment by stevenschlansker** [comment]
Hoping that this is fixed in the 2.60 release.

**Comment by natnan** [comment]
FYI, 2.62 fixed this issue. Thank you.
